INSERT INTO INGREDIENT (INGREDIENT_TITLE, INGREDIENT_QUANTITY, INGREDIENT_EXPIRATION_DATE, INGREDIENT_PRICE, INGREDIENT_REQUIRED)
VALUES ('Coffee', 2500, '2021-12-31', 31.50, 1);
INSERT INTO INGREDIENT (INGREDIENT_TITLE, INGREDIENT_QUANTITY, INGREDIENT_EXPIRATION_DATE, INGREDIENT_PRICE, INGREDIENT_REQUIRED) VALUES
('Milk', 1000, '2021-12-31', 2.50, 1);
INSERT INTO INGREDIENT (INGREDIENT_TITLE, INGREDIENT_QUANTITY, INGREDIENT_EXPIRATION_DATE, INGREDIENT_PRICE, INGREDIENT_REQUIRED)
VALUES ('Chocolate', 1000, '2021-12-31', 8.35, 1);
INSERT INTO INGREDIENT (INGREDIENT_TITLE, INGREDIENT_QUANTITY, INGREDIENT_EXPIRATION_DATE, INGREDIENT_PRICE, INGREDIENT_REQUIRED)
VALUES ('Water', 1000, '2021-12-31', 0.63, 1);
INSERT INTO INGREDIENT (INGREDIENT_TITLE, INGREDIENT_QUANTITY, INGREDIENT_EXPIRATION_DATE, INGREDIENT_PRICE, INGREDIENT_REQUIRED)
VALUES ('Sugar', 1000, '2021-12-31', 1.68, 0);
INSERT INTO INGREDIENT (INGREDIENT_TITLE, INGREDIENT_QUANTITY, INGREDIENT_EXPIRATION_DATE, INGREDIENT_PRICE, INGREDIENT_REQUIRED)
VALUES ('Syrup', 400, '2021-12-31', 3.25, 0);
INSERT INTO INGREDIENT (INGREDIENT_TITLE, INGREDIENT_QUANTITY, INGREDIENT_EXPIRATION_DATE, INGREDIENT_PRICE, INGREDIENT_REQUIRED)
VALUES ('Cinnamon', 100, '2021-12-31', 5.24, 0);
INSERT INTO INGREDIENT (INGREDIENT_TITLE, INGREDIENT_QUANTITY, INGREDIENT_EXPIRATION_DATE, INGREDIENT_PRICE, INGREDIENT_REQUIRED)
VALUES ('Cup', 250, '2025-12-31', 19.00, 1);
INSERT INTO INGREDIENT (INGREDIENT_TITLE, INGREDIENT_QUANTITY, INGREDIENT_EXPIRATION_DATE, INGREDIENT_PRICE, INGREDIENT_REQUIRED)
VALUES ('Teaspoon', 250, '2025-12-31', 9.99, 1);

INSERT INTO BEVERAGE (BEVERAGE_TITLE, BEVERAGE_ING_COFFEE, BEVERAGE_ING_MILK, BEVERAGE_ING_CHOCOLATE, BEVERAGE_ING_WATER,
BEVERAGE_ING_SUGAR, BEVERAGE_ING_SYRUP, BEVERAGE_ING_CINNAMON, BEVERAGE_HIDDEN) VALUES ('Espresso', 30, 0, 0, 0, 1, 0, 1, 1);
INSERT INTO BEVERAGE (BEVERAGE_TITLE, BEVERAGE_ING_COFFEE, BEVERAGE_ING_MILK, BEVERAGE_ING_CHOCOLATE, BEVERAGE_ING_WATER,
BEVERAGE_ING_SUGAR, BEVERAGE_ING_SYRUP, BEVERAGE_ING_CINNAMON, BEVERAGE_HIDDEN) VALUES ('Double Espresso', 60, 0, 0, 0, 1, 0, 1, 1);
INSERT INTO BEVERAGE (BEVERAGE_TITLE, BEVERAGE_ING_COFFEE, BEVERAGE_ING_MILK, BEVERAGE_ING_CHOCOLATE, BEVERAGE_ING_WATER,
BEVERAGE_ING_SUGAR, BEVERAGE_ING_SYRUP, BEVERAGE_ING_CINNAMON, BEVERAGE_HIDDEN) VALUES ('Americano', 60, 0, 0, 90, 1, 0, 1, 1);
INSERT INTO BEVERAGE (BEVERAGE_TITLE, BEVERAGE_ING_COFFEE, BEVERAGE_ING_MILK, BEVERAGE_ING_CHOCOLATE, BEVERAGE_ING_WATER,
BEVERAGE_ING_SUGAR, BEVERAGE_ING_SYRUP, BEVERAGE_ING_CINNAMON, BEVERAGE_HIDDEN) VALUES ('Cappuccino', 30, 50, 0, 0, 1, 1, 1, 1);
INSERT INTO BEVERAGE (BEVERAGE_TITLE, BEVERAGE_ING_COFFEE, BEVERAGE_ING_MILK, BEVERAGE_ING_CHOCOLATE, BEVERAGE_ING_WATER,
BEVERAGE_ING_SUGAR, BEVERAGE_ING_SYRUP, BEVERAGE_ING_CINNAMON, BEVERAGE_HIDDEN) VALUES ('Latte', 30, 100, 0, 0, 1, 1, 1, 1);
INSERT INTO BEVERAGE (BEVERAGE_TITLE, BEVERAGE_ING_COFFEE, BEVERAGE_ING_MILK, BEVERAGE_ING_CHOCOLATE, BEVERAGE_ING_WATER,
BEVERAGE_ING_SUGAR, BEVERAGE_ING_SYRUP, BEVERAGE_ING_CINNAMON, BEVERAGE_HIDDEN) VALUES ('Mocachino', 30, 30, 30, 0, 1, 1, 1, 1);