CREATE TABLE INGREDIENT
(
    INGREDIENT_ID SERIAL,
    INGREDIENT_TITLE VARCHAR(50) UNIQUE,
    INGREDIENT_QUANTITY INT,
    INGREDIENT_EXPIRATION_DATE DATE,
    INGREDIENT_PRICE NUMERIC(6,2),
    INGREDIENT_REQUIRED BOOLEAN
);