CREATE TABLE BEVERAGE
(
    BEVERAGE_ID SERIAL,
    BEVERAGE_TITLE VARCHAR(50) UNIQUE,
    BEVERAGE_ING_COFFEE INT,
    BEVERAGE_ING_MILK INT,
    BEVERAGE_ING_CHOCOLATE INT,
    BEVERAGE_ING_WATER INT,
    BEVERAGE_ING_SUGAR BOOLEAN,
    BEVERAGE_ING_SYRUP BOOLEAN,
    BEVERAGE_ING_CINNAMON BOOLEAN,
    BEVERAGE_HIDDEN BOOLEAN
);